version: "3.8"

# docker-compose -f .\docker-compose.yml up

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/Databases/dev.archive
      - ./database/production:/Databases/production

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:123@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"

  # server-app:
  #   build: .
  #   image: golang-server
  #   ports:
  #     - "5000:5000"
  #   restart: unless-stopped
